# Generated by Django 4.1.13 on 2023-12-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_user_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Store',
        ),
    ]
