# Generated by Django 4.1.13 on 2023-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Fashion', 'Fashion'), ('Education', 'Education')], max_length=20),
        ),
    ]
