# Generated by Django 4.1.13 on 2023-12-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename__id_products_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='_id',
        ),
    ]
