# Generated by Django 4.1.13 on 2023-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_rename_id_products__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
