# Generated by Django 4.1.13 on 2023-12-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='_id',
            new_name='item_id',
        ),
    ]
