# Generated by Django 4.1.13 on 2023-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_products_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='item_id',
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
