# Generated by Django 4.1.13 on 2023-12-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
