# Generated by Django 4.1.13 on 2023-12-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='id',
            new_name='contact_id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='prod_id',
        ),
    ]
