# Generated by Django 4.1.13 on 2023-12-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_remove_products_id_products__id_alter_contact__id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='_id',
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
