# Generated by Django 4.1.13 on 2024-01-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_address_products_image_delete_productimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
