# Generated by Django 4.1.13 on 2024-01-04 19:16

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_alter_address_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
