# Generated by Django 4.1.13 on 2024-01-04 19:18

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_alter_address_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_id',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
