# Generated by Django 4.1.13 on 2024-01-04 19:23

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_remove_address_address_id_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AddField(
            model_name='address',
            name='_id',
            field=models.AutoField(default=builtins.id, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
