# Generated by Django 4.1.13 on 2024-01-05 21:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_alter_address__id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=5000)),
            ],
        ),
    ]
