# Generated by Django 4.1.13 on 2024-01-06 22:05

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_remove_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AddField(
            model_name='products',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
