# Generated by Django 4.1.13 on 2024-01-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_remove_products_id_products__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='_id',
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
