# Generated by Django 4.1.13 on 2024-01-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
