# Generated by Django 4.1.13 on 2024-01-12 18:14

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_remove_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_id',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, to='products.address'),
            preserve_default=False,
        ),
    ]
