# Generated by Django 4.1.13 on 2024-01-15 17:30

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_address_item_json_alter_address_name_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='item_json',
        ),
    ]
