# Generated by Django 4.1.13 on 2024-01-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_order_remove_address_item_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='code',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(default='', help_text='+12345678', max_length=20),
        ),
    ]
