# Generated by Django 4.1.13 on 2024-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_address_code_alter_address_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_id',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
