# Generated by Django 4.1.13 on 2024-01-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_remove_order__id_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
