# Generated by Django 4.1.13 on 2024-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_alter_address__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
