# Generated by Django 4.1.13 on 2024-01-17 10:19

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0078_alter_address__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False),
        ),
    ]
